### ISSUE TITLE
Setup of local front-end does not work

### ISSUE THREAD

**Issue by Sambam2** [OpenOlitor/OpenOlitor#139]
I want to run the front-end (client-admin & client-kundenportal) locally to try out some changes to it. However, the setup following https://github.com/OpenOlitor/OpenOlitor/wiki/Doku-Technisch_Client_Ent-Setup does not work as expected. According to the .nvmrc file, Node v18.12.1 should be used, but so far I only got it working with Node v15.14.0 (npm v7.7.6). When using a higher version of node, running npm install leads to : 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: grunt-connect-proxy@0.2.0
npm ERR! Found: grunt@1.5.3
npm ERR! node_modules/grunt
npm ERR!   dev grunt@"^1.5.3" from the root project
npm ERR!   peer grunt@">=0.4.1" from grunt-angular-gettext@2.5.3
npm ERR!   node_modules/grunt-angular-gettext
npm ERR!     dev grunt-angular-gettext@"^2.5.3" from the root project
npm ERR!   15 more (grunt-autoprefixer, grunt-concurrent, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer grunt@"~0.4.1" from grunt-connect-proxy@0.2.0
npm ERR! node_modules/grunt-connect-proxy
npm ERR!   dev grunt-connect-proxy@"^0.2.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: grunt@0.4.5
npm ERR! node_modules/grunt
npm ERR!   peer grunt@"~0.4.1" from grunt-connect-proxy@0.2.0
npm ERR!   node_modules/grunt-connect-proxy
npm ERR!     dev grunt-connect-proxy@"^0.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sam/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2023-04-07T17_51_41_701Z-debug-0.log
```
Then when running npm install with --legacy-peer-deps (for example) this leads to
```
npm ERR! Stack trace:
npm ERR! NestedError: Could not require module 'npm'
npm ERR!     at requireg (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/requireg/lib/requireg.js:14:11)
npm ERR!     at Object.<anonymous> (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower-npm-resolver/dist/npm/_load.js:28:11)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower-npm-resolver/dist/npm/versions.js:30:15)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR! Caused By: Error: The programmatic API was removed in npm v8.0.0
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/npm/index.js:4:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at requireg (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/requireg/lib/requireg.js:12:12)
npm ERR!     at Object.<anonymous> (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower-npm-resolver/dist/npm/_load.js:28:11)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR! 
npm ERR! Console trace:
npm ERR! Error
npm ERR!     at StandardRenderer.error (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/renderers/StandardRenderer.js:88:37)
npm ERR!     at Logger.<anonymous> (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/bin/bower.js:113:30)
npm ERR!     at Logger.emit (node:events:513:28)
npm ERR!     at Logger.emit (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
npm ERR!     at /Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/commands/index.js:49:24
npm ERR!     at _rejected (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/node_modules/q/q.js:864:24)
npm ERR!     at /Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/node_modules/q/q.js:890:30
npm ERR!     at Promise.when (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/node_modules/q/q.js:1142:31)
npm ERR!     at Promise.promise.promiseDispatch (/Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/node_modules/q/q.js:808:41)
npm ERR!     at /Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m/node_modules/bower/lib/node_modules/q/q.js:624:44
npm ERR! System info:
npm ERR! Bower version: 1.8.14
npm ERR! Node version: 18.15.0
npm ERR! OS: Darwin 22.4.0 arm64
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/sam/.npm/_cacache/tmp/git-clone4Gqc2m
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c bower install
```
as well as a ton of warning. Is there another way to let the front-end run locally and separate from the other services?

**Comment by AlwinEgger** [comment]
Sorry for the (large) delay!

I don't understand exactly what your request is: You want to run it on a higher node version, right?

Since this is (still) a Angular 1 application using bower I don't think it's easy to use a higher node version.
