### ISSUE TITLE
Fehler vom wss Websocket

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#38]
Beim testen mit der Docker-Version habe ich noch folgenden Fehler den ich im Server-Log angezeigt bekomme:

```
12:34:45.920UTC ERROR akka.actor.LocalActorRef oo-proxy-akka.actor.default-dispatcher-255 - Error during processing of request HttpRequest(GET,http://server:9003/openolitor/ws,List(Connection: upgrade, Host: server:9003, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0, Accept-Language: de-DE, en-US;q=0.7, en;q=0.3, Accept-Encoding: gzip, deflate, br, Sec-WebSocket-Version: 13, Origin: https://openolitor.MEINE-SOLAWI.de, Sec-WebSocket-Extensions: permessage-deflate, Sec-WebSocket-Key: wrMOyuElkKdr45i16S4piA==, DNT: 1, Cookie: activeLang=de_DE; _pk_id.13.81b5=92c7e5575346f6da.1596710333.2.1596716698.1596710858.; _pk_ses.13.81b5=1, Pragma: no-cache, Cache-Control: no-cache, X-Forwarded-Proto: https, X-Forwarded-For: 185.233.105.209, X-Forwarded-Host: openolitor.MEINE-SOLAWI.de, X-Forwarded-Server: openolitor.MEINE-SOLAWI.de),Empty,HTTP/1.1)
scala.MatchError: HttpRequest(GET,http://server:9003/openolitor/ws,List(Connection: upgrade, Host: server:9003, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0, Accept: */*, Accept-Language: de-DE, en-US;q=0.7, en;q=0.3, Accept-Encoding: gzip, deflate, br, Sec-WebSocket-Version: 13, Origin: https://openolitor.MEINE-SOLAWI.de, Sec-WebSocket-Extensions: permessage-deflate, Sec-WebSocket-Key: wrMOyuElkKdr45i16S4piA==, DNT: 1, Cookie: activeLang=de_DE; _pk_id.13.81b5=92c7e5575346f6da.1596710333.2.1596716698.1596710858.; _pk_ses.13.81b5=1, Pragma: no-cache, Cache-Control: no-cache, X-Forwarded-Proto: https, X-Forwarded-For: 185.233.105.209, X-Forwarded-Host: openolitor.MEINE-SOLAWI.de, X-Forwarded-Server: openolitor.MEINE-SOLAWI.de),Empty,HTTP/1.1) (of class spray.http.HttpRequest)
        at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253)
        at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:251)
        at spray.can.websocket.WebSocketServerWorker$$anonfun$handshaking$1.applyOrElse(WebSocketServerWorker.scala:26)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at ch.openolitor.core.proxy.ProxyWorker$$anonfun$2.applyOrElse(ProxyWorker.scala:82)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
        at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
        at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
        at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
        at spray.routing.HttpServiceActor.aroundReceive(HttpService.scala:96)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Das ganze läuft auf einem vServer hinter einem Apache, der alles als Reverse-Proxy durchreicht.
Meine ganzen Daten konnte ich kopieren und arbeiten/erstellen/ändern kann ich auch in der Weboberfläche. Allerdings wird mir auch immer der Server als offline angezeigt.
Hier noch zwei Bilder von der Version und der Fehlermeldung vom Firefox.
![2020-08-06 14_44_30-OpenOlitor](https://user-images.githubusercontent.com/20152200/89533833-4fdb8500-d7f4-11ea-9832-7d880ad5e007.png)
![2020-08-06 14_45_27-OpenOlitor](https://user-images.githubusercontent.com/20152200/89533843-52d67580-d7f4-11ea-8d97-0d2e03782ee8.png)

Wo kann ich hier weiter suchen wo das Problem liegt? Hat da jemand einen Tip?
Danke und Gruß Jan

PS: Sollen Issues alle hier in das Projekt oder soll ich die in den passenden Projekten erstellen? Da bin ich mir gerade unsicher :-)

**Comment by AlwinEgger** [comment]
Hier gibt es ein Problem mit dem WebSocket. Aus dem Grund wird der Status `Offline` angezeigt.
Den Fehler hatten wir auch schon und dazu gibt es ein internes Ticket. Wir müssen uns das Problem unbedingt anschauen.

Der Fehler liegt also nicht bei dir.

Du verwendest offenbar Firefox auf Windows, richtig?

Du hörst also von uns.

PS: Du kannst die Tickets gerne hier erfassen, denn solche Probleme sind ja nicht unbedingt klar dem Front- oder Backend zuzuordnen.

**Comment by budda85** [comment]
Ja das war Firefox auf Windows.
Ich teste es auch mal mit Arch-Linux und Firefox.

**Comment by budda85** [comment]
Meine Aussage

> Meine ganzen Daten konnte ich kopieren und arbeiten/erstellen/ändern kann ich auch in der Weboberfläche.

muss ich zurück ziehen, Ich kann leider keine Daten der Mitglieder ändern oder ein neues Mitglied hinzufügen.
Ich wollte mit der aktuellen Version die erstellung der SEPA-Datei testen und kann z. B. keine BIC bei einem Mitglied speichern.
Der Speicher-Button hat die ganze Zeit den "Ladekreis", aber eine Fehlermeldung oder ähnliches bekomme ich nicht.

**Comment by budda85** [comment]
Nochmal eine kleine Rückmeldung:
Auch mit Arch-Linux und Firefox oder Chromium habe ich die selben Probleme.
Gruß Jan

**Comment by AlwinEgger** [comment]
Zwei Rückfragen: 

Bist du mit deinem Clients auf einem Firmennetz oder ähnlich mit einem Proxy?

Verwendest du unseren nginx Server aus der Docker Compose configuration? Oder schaltest du selbst einen Proxy vor? Weil unsere interne Docker Compose Konfiguration enthält eine Regel für die Websockets:
https://github.com/OpenOlitor/openolitor-docker-compose/blob/master/config/nginx/nginx.conf#L89

Was ist, wenn du https://try.openolitor.ch aufrufst, funktioniert da der WebSocket?

**Comment by budda85** [comment]
Ich hatte es auf der Arbeit vom Firmennetzwerk aus probiert in welchem ich hinter einem Proxy bin und zuhause hatte ich es auch getestet wo ich "normales" Internet habe.

Ich habe die Docker konfiguration von euch so übernommen wie sie ist, habe allerdings den Port vom nginx auf 8090 geändert und davor läuft ein Apache Webserver als Reverse-Proxy.

Hier meine config vom Apache:

```
<VirtualHost xxx.xxx.xxx.xxx:443>
ServerName openolitor.XXXX.de

DocumentRoot /var/www/openolitor/mandant1
ProxyPass / http://127.0.0.1:8090/
ProxyPassReverse / http://127.0.0.1:8090/
ProxyPreserveHost On
ProxyAddHeaders On
RequestHeader set X-Forwarded-Proto "https"

SSLEngine on
SSLCertificateFile /etc/webmin/webmin/XXXX.de.cert
SSLCertificateKeyFile /etc/webmin/webmin/XXXX.de.key
SSLCACertificateFile /etc/webmin/webmin/XXXX.de.chain
SSLVerifyClient none
</VirtualHost>

<VirtualHost xxx.xxx.xxx.xxx:80>
ServerName openolitor.XXXX.de

DocumentRoot /var/www/openolitor/mandant1

RewriteEngine on
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [R=301,L]

ProxyPass / http://127.0.0.1:8090/
ProxyPassReverse / http://127.0.0.1:8090/
ProxyPreserveHost On
ProxyAddHeaders On
RequestHeader set X-Forwarded-Proto "http"
</VirtualHost>
```
So wie es aussieht funktioniert der Testserver zuhause mit dem Internet. Ich kann Mitglieder bearbeiten und speichern. Das ging bei meinem Testserver nicht. Morgen früh probiere ich es nochmal direkt im Firmennetzwerk ob da auch euer Testserver geht.

**Comment by AlwinEgger** [comment]
Hast du auf deinem Apache [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) aktiviert?

**Comment by budda85** [comment]
Das Modul habe ich aktiv, aber dein Gedanke stimmt vermutlich. Mein Proxy reicht den Websocket noch nicht richtig durch.
Der Websocket wird vom OO-Server bereitgestellt oder?

**Comment by AlwinEgger** [comment]
Ja genau.

**Comment by budda85** [comment]
Ja sch...., dass tut mir Leid.
Lag wirklich an meiner Apache config.
![grafik](https://user-images.githubusercontent.com/20152200/91432042-7758c700-e861-11ea-8dfd-21442f75de59.png)
Sorry, ich hoffe ihr habt hier nicht zuviel Arbeit rein gesteckt... :-(

**Comment by AlwinEgger** [comment]
Kein Problem. Gut ist das Problem gelöst.
